### ISSUE TITLE
PSD Todo

### ISSUE THREAD

**Issue by sundow441** [Miracle-Midnight/Drawing-Duo#26]
# Summary
react를 사용해 서버 - 클라이언트 간 API 연동
WebRTC로 음성 채팅 구현

# 완료 조건

- [ ] 로그인 페이지 API 연동

- [ ] 회원 가입 페이지 API 연동

- [ ] 로비 페이지 API 연동

- [ ] 대기실 페이지 API 연동

- [ ] 인게임 화면 페이지 API 연동

- [ ] 결과창 페이지 API 연동

- [ ] 음성 채팅 구현
